import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  await prisma.fuzzyRule.createMany({
    data: [
      {
        ageRange: '0-6 bulan',
        weightMin: 2.5,
        weightMax: 4.5,
        heightMin: 45,
        heightMax: 65,
        zsTbuMin: -5,
        zsTbuMax: -2,
        zsBBuMin: -5,
        zsBBuMax: -2,
        output: 'STUNTING',
      },
      {
        ageRange: '0-6 bulan',
        weightMin: 4.6,
        weightMax: 6.5,
        heightMin: 66,
        heightMax: 75,
        zsTbuMin: -2,
        zsTbuMax: 3,
        zsBBuMin: -2,
        zsBBuMax: 1,
        output: 'NORMAL',
      },
      {
        ageRange: '6-12 bulan',
        weightMin: 5.5,
        weightMax: 8.5,
        heightMin: 65,
        heightMax: 80,
        zsTbuMin: -5,
        zsTbuMax: -2,
        zsBBuMin: -5,
        zsBBuMax: -2,
        output: 'STUNTING',
      },
      {
        ageRange: '6-12 bulan',
        weightMin: 8.6,
        weightMax: 10.5,
        heightMin: 81,
        heightMax: 90,
        zsTbuMin: -2,
        zsTbuMax: 3,
        zsBBuMin: -2,
        zsBBuMax: 1,
        output: 'NORMAL',
      },
      {
        ageRange: '12-24 bulan',
        weightMin: 8.0,
        weightMax: 12.0,
        heightMin: 75,
        heightMax: 90,
        zsTbuMin: -5,
        zsTbuMax: -2,
        zsBBuMin: -5,
        zsBBuMax: -2,
        output: 'STUNTING',
      },
      {
        ageRange: '12-24 bulan',
        weightMin: 12.1,
        weightMax: 15.0,
        heightMin: 91,
        heightMax: 100,
        zsTbuMin: -2,
        zsTbuMax: 3,
        zsBBuMin: -2,
        zsBBuMax: 1,
        output: 'NORMAL',
      },
      {
        ageRange: '24-36 bulan',
        weightMin: 10.0,
        weightMax: 13.5,
        heightMin: 85,
        heightMax: 95,
        zsTbuMin: -5,
        zsTbuMax: -2,
        zsBBuMin: -5,
        zsBBuMax: -2,
        output: 'STUNTING',
      },
      {
        ageRange: '24-36 bulan',
        weightMin: 13.6,
        weightMax: 16.0,
        heightMin: 96,
        heightMax: 105,
        zsTbuMin: -2,
        zsTbuMax: 3,
        zsBBuMin: -2,
        zsBBuMax: 1,
        output: 'NORMAL',
      },
      {
        ageRange: '36-48 bulan',
        weightMin: 12.0,
        weightMax: 16.0,
        heightMin: 95,
        heightMax: 105,
        zsTbuMin: -5,
        zsTbuMax: -2,
        zsBBuMin: -5,
        zsBBuMax: -2,
        output: 'STUNTING',
      },
      {
        ageRange: '36-48 bulan',
        weightMin: 16.1,
        weightMax: 18.5,
        heightMin: 106,
        heightMax: 115,
        zsTbuMin: -2,
        zsTbuMax: 3,
        zsBBuMin: -2,
        zsBBuMax: 1,
        output: 'NORMAL',
      },
      {
        ageRange: '48-60 bulan',
        weightMin: 14.0,
        weightMax: 18.0,
        heightMin: 105,
        heightMax: 115,
        zsTbuMin: -5,
        zsTbuMax: -2,
        zsBBuMin: -5,
        zsBBuMax: -2,
        output: 'STUNTING',
      },
      {
        ageRange: '48-60 bulan',
        weightMin: 18.1,
        weightMax: 22.0,
        heightMin: 116,
        heightMax: 125,
        zsTbuMin: -2,
        zsTbuMax: 3,
        zsBBuMin: -2,
        zsBBuMax: 1,
        output: 'NORMAL',
      },
    ],
  });

  await prisma.variableFuzzy.createMany({
    data: [
      {
        age: 'MUDA',
        height: 'NORMAL',
        weight: 'NORMAL',
        zsTBU: 'NORMAL',
        zsBBU: 'NORMAL',
        output: 'NORMAL',
      },
      {
        age: 'TUA',
        height: 'PENDEK',
        weight: 'KURANG',
        zsTBU: 'KURANG',
        zsBBU: 'KURANG',
        output: 'STUNTING',
      },
      {
        age: 'MUDA',
        height: 'PENDEK',
        weight: 'KURANG',
        zsTBU: 'NORMAL',
        zsBBU: 'KURANG',
        output: 'STUNTING',
      },
      {
        age: 'MUDA',
        height: 'NORMAL',
        weight: 'KURANG',
        zsTBU: 'NORMAL',
        zsBBU: 'NORMAL',
        output: 'NORMAL',
      },
      {
        age: 'MUDA',
        height: 'PENDEK',
        weight: 'KURANG',
        zsTBU: 'KURANG',
        zsBBU: 'KURANG',
        output: 'STUNTING',
      },
      {
        age: 'TUA',
        height: 'PENDEK',
        weight: 'KURANG',
        zsTBU: 'NORMAL',
        zsBBU: 'NORMAL',
        output: 'STUNTING',
      },
      {
        age: 'TUA',
        height: 'NORMAL',
        weight: 'NORMAL',
        zsTBU: 'NORMAL',
        zsBBU: 'NORMAL',
        output: 'NORMAL',
      },
      {
        age: 'TUA',
        height: 'PENDEK',
        weight: 'NORMAL',
        zsTBU: 'KURANG',
        zsBBU: 'NORMAL',
        output: 'STUNTING',
      },
    ],
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
